### ISSUE TITLE
StringIndexOutOfBoundsException for "+" style git.eclipse.org commit id

### ISSUE THREAD

**Issue by ewillink** [eclipse-justj/justj#20]
Using the 'correct' commit id spelling

-commit https://git.eclipse.org/r/plugins/gitiles/mmt/org.eclipse.qvto/+/03dcf461d09c9eda43fc657843875e3de241a7e8

the JustJ generator crashes with

java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 105
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
	at java.base/java.lang.String.substring(String.java:2704)
	at org.eclipse.justj.p2.UpdateSiteIndexGenerator.getCommitsURL(UpdateSiteIndexGenerator.java:1006)
	at org.eclipse.justj.p2.UpdateSiteIndex.generate(UpdateSiteIndex.java:711)
	at org.eclipse.justj.p2.UpdateSiteGenerator.generateIndex(UpdateSiteGenerator.java:1332)
	at org.eclipse.justj.p2.UpdateSiteGenerator.generateIndex(UpdateSiteGenerator.java:1358)
	at org.eclipse.justj.p2.UpdateSiteGenerator.generateIndex(UpdateSiteGenerator.java:1358)
	at org.eclipse.justj.p2.UpdateSiteGenerator.generateIndex(UpdateSiteGenerator.java:1217)
	at org.eclipse.justj.p2.P2Manager.generateUpdateSiteIndex(P2Manager.java:459)

Using the 'incorrect' commit id

-commit https://git.eclipse.org/r/plugins/gitiles/mmt/org.eclipse.qvto/commit/03dcf461d09c9eda43fc657843875e3de241a7e8

the JustJ generator succeeds but clicking on the commit link [https://git.eclipse.org/r/plugins/gitiles/mmt/org.eclipse.qvto/commit/03dcf461d09c9eda43fc657843875e3de241a7e8](url) leads to "Request not authorized"

**Comment by ewillink** [comment]
Thanks. I find "c" and "r" pretty confusing too. Seems like a good tool got messed up by failing to rationalize add-ons.

**Comment by merks** [comment]
Given that git.eclipse.org is being phased out, I don't want to invest effort to make gittiles work, of even to bother with documentation about that.
